[package]
name = "rust_gcd"
version = "0.1.0"
authors = ["xue35@rpi400 <xue@live.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
