[package]
name = "rust-yew"
version = "0.1.0"
authors = ["xue35@rpi400 <xue@live.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"

